# Generated by Django 4.2.30 on 2026-04-12 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couriers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierassignment',
            name='courier',
            field=models.ForeignKey(limit_choices_to={'role': 'courier'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
